spring.application.name=tiendajurasic3

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/jurassic_shop_in5bv?useSSL=false
spring.datasource.username=IN5BV
spring.datasource.password=_@miNdAa5V
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
